plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
    id 'java'
}


group = 'com.vroomvroom'
version = '0.0.1-SNAPSHOT'
description = 'eureka-server'

//java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(17)
//    }
//}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
