spring:
  application:
    name: hub-service
  config:
    import: optional:file:.env[.properties]
  web:
    resources:
      add-mappings: false

  profiles:
    active: local
    group:
      local: local
      prod: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/hub_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: default

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka