spring:
  application:
    name: hub-service
  config:
    import: optional:file:.env[.properties]
  web:
    resources:
      add-mappings: false

  profiles:
    active: local
    group:
      local: local
      prod: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/hub_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: default

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/hub-service/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 19092