spring:
  application:
    name: gateway-service
  web:
    resources:
      add-mappings: false

  profiles:
    active: local
    group:
      local: local
      prod: prod

  config:
    import: optional:file:.env[.properties]

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # 회원가입 / 로그인 (JWT 인증 제외)
        - id: user-auth-free
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/signup, /api/v1/auth/login

        # 유저 서비스 (JWT 인증 필요)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthFilter
            - AuthPermissionFilter

        # 허브 서비스 (JWT 인증 필요)
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**
          filters:
            - AuthFilter
            - AuthPermissionFilter

        # 주문 서비스 (JWT 인증 필요)
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthFilter
            - AuthPermissionFilter

  jwt:
    secret: ${JWT_SECRET_KEY}

server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}