spring:
  application:
    name: delivery-service
  config:
    import: optional:file:.env[.properties]
  web:
    resources:
      add-mappings: false

  profiles:
    active: local
    group:
      local: local
      prod: prod

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DELIVERY_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: redis
      port: 6379

  cloud:
    openfeign:
      circuitbreaker:
        enabled: false

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: delivery-assignment-group
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_URL}

app:
  kafka:
    topics:
      manager-assignment: "manager-assignment-topic"

  redis:
    keys:
      init-lock: "global:hub_manager:init_lock"
      replay-lock: "global:hub_manager:replay_lock"
      manager-queue: "global:hub_manager:queue"